sources:
  - name: BRONZE_STAGE
    database: DATA_INGESTION_SOLUTION  
    schema: BRONZE_STAGE
    tables:
      - name: activities
      - name: agencies_servicelines
      - name: agencies_servicelines_branches
      - name: authorization
      - name: authorization_disciplines
      - name: authorization_unit_types
      - name: branch_business_hours
      - name: branch_discipline_costs
      - name: branch_renewable_requirements
      - name: branches
      - name: careplans
      - name: ccd_alerts
      - name: ccd_medications
      - name: client_address
      - name: client_admissions
      - name: client_contacts
      - name: client_diagnoses_and_procedures
      - name: client_electronic_signature_forms
      - name: client_episode_adt_pharmacia
      - name: client_episode_careplan
      - name: client_episode_claim_medications
      - name: client_episode_contacts
      - name: client_episode_date_of_death
      - name: client_episode_fs
      - name: client_episode_hiu_alerts
      - name: client_episode_inpatient_events
      - name: client_episode_oasis
      - name: client_episode_oasis_answers
      - name: client_episode_oasis_grouper_scores
      - name: client_episode_related_facilities
      - name: client_episode_visit_notes
      - name: client_episode_visits_all
      - name: client_episodes_all
      - name: client_meds
      - name: client_orders_all
      - name: client_sched_visits
      - name: clients_all
      - name: diagnosis_categories
      - name: diagnosis_info
      - name: disciplines
      - name: documents
      - name: facilities
      - name: facility_branches
      - name: facility_contractbed_rates
      - name: med_classifications
      - name: medication_statuses
      - name: oasis_assessments
      - name: oasis_mos
      - name: oasis_questions
      - name: oasis_responses
      - name: order_types
      - name: patient_med_attributes
      - name: patient_meds
      - name: patient_outcome_predictive_modeling_risk_results
      - name: payor_source_branches
      - name: payor_sources
      - name: payor_types
      - name: physician_groups
      - name: physician_offices
      - name: physicians
      - name: pps_score
      - name: ppstimecards
      - name: program_names
      - name: programs
      - name: referral_diagnosis
      - name: referral_request_rejection_reasons
      - name: referral_requests
      - name: referral_sources
      - name: referring_facility_types
      - name: sched
      - name: service_line
      - name: service_line_subtypes
      - name: service_line_types
      - name: servicecodes
      - name: servicecodes_servicelines
      - name: tbl_client_log_cleansed
      - name: tbl_note_type_cleansed
      - name: visit_types
      - name: worker_base
      - name: worker_branches
      - name: worker_intelligent_scheduling_address
      - name: worker_jobdescriptions
      - name: worker_service_lines