{# Automated Python Compilation for Pipeline: CLIENT_SCHED_VISITS_PL #}
{{
    config(
        materialized='incremental',
        unique_key='CSV_ID',
        incremental_strategy='merge',
        alias='CLIENT_SCHED_VISITS_HCHB_CLEANSED'
    )
}}

SELECT
    NULLIF(TRIM(TRIM("CSV_VDID")), '') AS "CSV_VDID",
    NULLIF(TRIM(TRIM("CSV_ACCEPTED")), '') AS "CSV_ACCEPTED",
    NULLIF(TRIM(TRIM("CDC_OP")), '') AS "CDC_OP",
    NULLIF(TRIM(TRIM("CSV_ID")), '') AS "CSV_ID",
    NULLIF(TRIM(TRIM("CSV_VRID")), '') AS "CSV_VRID",
    NULLIF(TRIM(TRIM("CSV_EPIID")), '') AS "CSV_EPIID",
    NULLIF(TRIM(TRIM("CSV_AGID")), '') AS "CSV_AGID",
    NULLIF(TRIM(TRIM("CSV_SYNCHID")), '') AS "CSV_SYNCHID",
    NULLIF(TRIM(TRIM("CSV_DCRID")), '') AS "CSV_DCRID",
    NULLIF(TRIM(TRIM("CSV_ENDTIME")), '') AS "CSV_ENDTIME",
    NULLIF(TRIM(TRIM("CSV_SCID")), '') AS "CSV_SCID",
    UPPER(REGEXP_REPLACE(NULLIF(TRIM(TRIM("CSV_STATUS")), ''), '[^A-Za-z ]+', '')) AS "CSV_STATUS",
    NULLIF(TRIM(TRIM("CSV_DCCID")), '') AS "CSV_DCCID",
    TRY_TO_TIMESTAMP(REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(NULLIF(TRIM(TRIM("CSV_INSERTDATE")), ''), '[^0-9/.-]+', ''), '[/.]', '-'), '-{2,}', '-')) AS "CSV_INSERTDATE",
    NULLIF(TRIM(TRIM("CSV_VISITNUMBER")), '') AS "CSV_VISITNUMBER",
    NULLIF(TRIM(TRIM("CSV_CEFSID")), '') AS "CSV_CEFSID",
    TRY_TO_TIMESTAMP(REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(NULLIF(TRIM(TRIM("CSV_LASTUPDATE")), ''), '[^0-9/.-]+', ''), '[/.]', '-'), '-{2,}', '-')) AS "CSV_LASTUPDATE",
    NULLIF(TRIM(TRIM("CSV_VMID")), '') AS "CSV_VMID",
    NULLIF(TRIM(TRIM("CSV_VSID")), '') AS "CSV_VSID",
    NULLIF(TRIM(TRIM("CSV_NEEDSPROCESSING")), '') AS "CSV_NEEDSPROCESSING",
    NULLIF(TRIM(TRIM("CSV_BEGTIME")), '') AS "CSV_BEGTIME",
    NULLIF(TRIM(TRIM("CSV_PAID")), '') AS "CSV_PAID",
    NULLIF(TRIM(TRIM("CSV_MISSED")), '') AS "CSV_MISSED",
    TRY_TO_DATE(
    CASE
      WHEN REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(NULLIF(TRIM(TRIM("CSV_SCHEDDATE")), ''), '[^0-9/.-]+', ''), '[/.]', '-'), '-{2,}', '-') IS NULL THEN NULL
      WHEN REGEXP_LIKE(REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(NULLIF(TRIM(TRIM("CSV_SCHEDDATE")), ''), '[^0-9/.-]+', ''), '[/.]', '-'), '-{2,}', '-'), '^[0-9]{4}-[0-9]{1,2}-[0-9]{1,2}$') THEN REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(NULLIF(TRIM(TRIM("CSV_SCHEDDATE")), ''), '[^0-9/.-]+', ''), '[/.]', '-'), '-{2,}', '-')
      WHEN REGEXP_LIKE(REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(NULLIF(TRIM(TRIM("CSV_SCHEDDATE")), ''), '[^0-9/.-]+', ''), '[/.]', '-'), '-{2,}', '-'), '^[0-9]{1,2}-[0-9]{1,2}-[0-9]{4}$')
        THEN SPLIT_PART(REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(NULLIF(TRIM(TRIM("CSV_SCHEDDATE")), ''), '[^0-9/.-]+', ''), '[/.]', '-'), '-{2,}', '-'), '-', 3) || '-' ||
             LPAD(SPLIT_PART(REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(NULLIF(TRIM(TRIM("CSV_SCHEDDATE")), ''), '[^0-9/.-]+', ''), '[/.]', '-'), '-{2,}', '-'), '-', 2), 2, '0') || '-' ||
             LPAD(SPLIT_PART(REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(NULLIF(TRIM(TRIM("CSV_SCHEDDATE")), ''), '[^0-9/.-]+', ''), '[/.]', '-'), '-{2,}', '-'), '-', 1), 2, '0')
      ELSE NULL
    END
) AS "CSV_SCHEDDATE",
    TRY_TO_TIMESTAMP(NULLIF(TRIM(TRIM("CDC_TS")), '')) AS "CDC_TS",
    NULLIF(TRIM(TRIM("CSV_AUTHID")), '') AS "CSV_AUTHID",
    NULLIF(TRIM("INSERTED_DATE"), '') AS "INSERTED_DATE",
    NULLIF(TRIM(TRIM("INSERTED_BY")), '') AS "INSERTED_BY",
    NULLIF(TRIM("UPDATED_DATE"), '') AS "UPDATED_DATE"

FROM DATA_INGESTION_SOLUTION.BRONZE_HCHB.CLIENT_SCHED_VISITS

{% if is_incremental() %}
  WHERE "UPDATED_DATE" > DATEADD(minute, -5, (SELECT MAX("UPDATED_DATE") FROM {{ this }}))
{% endif %}
