{# Automated Python Compilation for Pipeline: DISCIPLINES_PL #}
{{
    config(
        materialized='incremental',
        unique_key='DSC_ID',
        incremental_strategy='merge',
        alias='DISCIPLINES_HCHB_CLEANSED'
    )
}}

SELECT
    TRY_TO_TIMESTAMP(NULLIF(TRIM(TRIM("CDC_TS")), '')) AS "CDC_TS",
    NULLIF(TRIM(TRIM("DSC_ID")), '') AS "DSC_ID",
    TRY_TO_TIMESTAMP(REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(NULLIF(TRIM(TRIM("DSC_INSERTDATE")), ''), '[^0-9/.-]+', ''), '[/.]', '-'), '-{2,}', '-')) AS "DSC_INSERTDATE",
    TRY_TO_TIMESTAMP(REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(NULLIF(TRIM(TRIM("DT_LASTUPDATE")), ''), '[^0-9/.-]+', ''), '[/.]', '-'), '-{2,}', '-')) AS "DT_LASTUPDATE",
    NULLIF(TRIM(TRIM("DSC_REVENUECODE")), '') AS "DSC_REVENUECODE",
    NULLIF(TRIM(TRIM("DSC_RATE")), '') AS "DSC_RATE",
    NULLIF(TRIM(TRIM("DSC_CODE")), '') AS "DSC_CODE",
    NULLIF(TRIM(TRIM("DSC_DESC")), '') AS "DSC_DESC",
    NULLIF(TRIM(TRIM("CDC_OP")), '') AS "CDC_OP",
    NULLIF(TRIM(TRIM("DSC_ACTIVE")), '') AS "DSC_ACTIVE",
    NULLIF(TRIM("INSERTED_DATE"), '') AS "INSERTED_DATE",
    NULLIF(TRIM(TRIM("INSERTED_BY")), '') AS "INSERTED_BY",
    NULLIF(TRIM("UPDATED_DATE"), '') AS "UPDATED_DATE"

FROM DATA_INGESTION_SOLUTION.BRONZE_HCHB.DISCIPLINES
