{# Automated Python Compilation for Pipeline: FACILITIES_PL #}
{{
    config(
        materialized='incremental',
        unique_key='FA_ID',
        incremental_strategy='merge',
        alias='FACILITIES_HCHB_CLEANSED'
    )
}}

SELECT
    NULLIF(TRIM(TRIM("FA_NPI")), '') AS "FA_NPI",
    NULLIF(TRIM(TRIM("FA_FAXVISITNOTE")), '') AS "FA_FAXVISITNOTE",
    NULLIF(TRIM(TRIM("FA_RRTID")), '') AS "FA_RRTID",
    NULLIF(TRIM(TRIM("FA_REFERRINGFACILITY")), '') AS "FA_REFERRINGFACILITY",
    NULLIF(TRIM(TRIM("FA_PARENTCOMPANY")), '') AS "FA_PARENTCOMPANY",
    NULLIF(TRIM(TRIM("FA_LONGITUDE")), '') AS "FA_LONGITUDE",
    NULLIF(TRIM(TRIM("FA_HOSPICEINPATIENTENCOUNTERS")), '') AS "FA_HOSPICEINPATIENTENCOUNTERS",
    NULLIF(TRIM(TRIM("FA_VNWEB")), '') AS "FA_VNWEB",
    TRY_TO_TIMESTAMP(NULLIF(TRIM(TRIM("CDC_TS")), '')) AS "CDC_TS",
    REGEXP_REPLACE(NULLIF(TRIM(TRIM("FA_SSN")), ''), '[^0-9]+', '') AS "FA_SSN",
    NULLIF(TRIM(TRIM("FA_INPATIENTFACILITY")), '') AS "FA_INPATIENTFACILITY",
    CASE 
     WHEN NULLIF(TRIM(TRIM("FA_ZIP")), '') IS NULL THEN NULL
     ELSE REGEXP_REPLACE(NULLIF(TRIM(TRIM("FA_ZIP")), ''), '[^0-9]+', '')
 END AS "FA_ZIP",
    INITCAP(REGEXP_REPLACE(NULLIF(TRIM(TRIM("FA_STATE")), ''), '[^A-Za-z ]+', '')) AS "FA_STATE",
    TRY_TO_TIMESTAMP(REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(NULLIF(TRIM(TRIM("FA_INSERTDATE")), ''), '[^0-9/.-]+', ''), '[/.]', '-'), '-{2,}', '-')) AS "FA_INSERTDATE",
    NULLIF(TRIM(TRIM("FA_RFTID")), '') AS "FA_RFTID",
    TRIM(REGEXP_REPLACE(REGEXP_REPLACE(NULLIF(TRIM(TRIM("FA_STREET")), ''), '[^A-Za-z0-9 ,.#/()_-]+', ''), '[[:space:]]+', ' ')) AS "FA_STREET",
    NULLIF(TRIM(TRIM("FA_LATLONGMETHOD")), '') AS "FA_LATLONGMETHOD",
    TRY_TO_TIMESTAMP(REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(NULLIF(TRIM(TRIM("FA_LASTUPDATE")), ''), '[^0-9/.-]+', ''), '[/.]', '-'), '-{2,}', '-')) AS "FA_LASTUPDATE",
    NULLIF(TRIM(TRIM("FA_INCLUDEONCLAIMS")), '') AS "FA_INCLUDEONCLAIMS",
    NULLIF(TRIM(TRIM("FA_ID")), '') AS "FA_ID",
    NULLIF(TRIM(TRIM("FA_STAFFINGFACILITY")), '') AS "FA_STAFFINGFACILITY",
    NULLIF(TRIM(TRIM("FA_LATITUDE")), '') AS "FA_LATITUDE",
    IFF(UPPER(INITCAP(REGEXP_REPLACE(NULLIF(TRIM(TRIM("FA_NAME")), ''), '[^A-Za-z ]+', ''))) IN ('TEST','NA','N/A','UNKNOWN','DUMMY','NONE','DEFAULT'), NULL, INITCAP(REGEXP_REPLACE(NULLIF(TRIM(TRIM("FA_NAME")), ''), '[^A-Za-z ]+', ''))) AS "FA_NAME",
    NULLIF(TRIM(TRIM("FA_OUTPATIENTTREATMENTPROVIDER")), '') AS "FA_OUTPATIENTTREATMENTPROVIDER",
    NULLIF(TRIM(TRIM("CDC_OP")), '') AS "CDC_OP",
    NULLIF(TRIM(TRIM("FA_ACTIVE")), '') AS "FA_ACTIVE",
    NULLIF(TRIM(TRIM("FA_GLCODE")), '') AS "FA_GLCODE",
    NULLIF(TRIM(TRIM("FA_PMID")), '') AS "FA_PMID",
    NULLIF(REGEXP_REPLACE(IFF(LENGTH(REGEXP_REPLACE(NULLIF(TRIM(TRIM("FA_TELEPHONE")), ''), '[^0-9]+', '')) IN (10), REGEXP_REPLACE(NULLIF(TRIM(TRIM("FA_TELEPHONE")), ''), '[^0-9]+', ''), NULL), '^(0+|1+|2+|3+|4+|5+|6+|7+|8+|9+)$', ''), '') AS "FA_TELEPHONE",
    NULLIF(TRIM(TRIM("FA_ROOMANDBOARDRATE")), '') AS "FA_ROOMANDBOARDRATE",
    NULLIF(TRIM(TRIM("FA_WEBACCESS")), '') AS "FA_WEBACCESS",
    NULLIF(TRIM(TRIM("FA_FAX")), '') AS "FA_FAX",
    NULLIF(TRIM(TRIM("FA_MEDICAIDNUMBER")), '') AS "FA_MEDICAIDNUMBER",
    INITCAP(REGEXP_REPLACE(NULLIF(TRIM(TRIM("FA_CITY")), ''), '[^A-Za-z ]+', '')) AS "FA_CITY",
    NULLIF(TRIM(TRIM("FA_COMMENT")), '') AS "FA_COMMENT",
    NULLIF(TRIM(TRIM("FA_LIMITSMARTSCHEDULING")), '') AS "FA_LIMITSMARTSCHEDULING",
    NULLIF(TRIM(TRIM("FA_EIN")), '') AS "FA_EIN",
    NULLIF(TRIM("INSERTED_DATE"), '') AS "INSERTED_DATE",
    NULLIF(TRIM(TRIM("INSERTED_BY")), '') AS "INSERTED_BY",
    NULLIF(TRIM("UPDATED_DATE"), '') AS "UPDATED_DATE"

FROM DATA_INGESTION_SOLUTION.BRONZE_HCHB.FACILITIES
