{# Automated Python Compilation for Pipeline: PAYOR_SOURCES_PL #}
{{
    config(
        materialized='incremental',
        unique_key='PS_ID',
        incremental_strategy='merge',
        alias='PAYOR_SOURCES_HCHB_CLEANSED'
    )
}}

SELECT
    NULLIF(TRIM(TRIM("PS_INCLUDEINSSELFPAYVISITNOTES")), '') AS "PS_INCLUDEINSSELFPAYVISITNOTES",
    NULLIF(TRIM(TRIM("PS_DEFAULT_CPID")), '') AS "PS_DEFAULT_CPID",
    NULLIF(TRIM(TRIM("PS_SBID")), '') AS "PS_SBID",
    NULLIF(TRIM(TRIM("PS_LENGTHOFEPISODE")), '') AS "PS_LENGTHOFEPISODE",
    NULLIF(TRIM(TRIM("PS_EXCLUDEINSVERIFYWORKFLOWONRECERTS")), '') AS "PS_EXCLUDEINSVERIFYWORKFLOWONRECERTS",
    NULLIF(TRIM(TRIM("PS_ALLOWPOCDIRECTENTRY")), '') AS "PS_ALLOWPOCDIRECTENTRY",
    INITCAP(REGEXP_REPLACE(NULLIF(TRIM(TRIM("PS_STATE")), ''), '[^A-Za-z ]+', '')) AS "PS_STATE",
    NULLIF(TRIM(TRIM("CDC_OP")), '') AS "CDC_OP",
    NULLIF(TRIM(TRIM("PS_PTID")), '') AS "PS_PTID",
    NULLIF(TRIM(TRIM("PS_ACTIVE")), '') AS "PS_ACTIVE",
    NULLIF(TRIM(TRIM("PS_ISMEDICAREREPLACEMENTPAYOR")), '') AS "PS_ISMEDICAREREPLACEMENTPAYOR",
    NULLIF(TRIM(TRIM("PS_ITID")), '') AS "PS_ITID",
    NULLIF(TRIM(TRIM("PS_TIMELYFILINGDAYS")), '') AS "PS_TIMELYFILINGDAYS",
    NULLIF(TRIM(TRIM("PS_ENABLEAUTOFINISHOFFAMILYCAREGIVERVISITS")), '') AS "PS_ENABLEAUTOFINISHOFFAMILYCAREGIVERVISITS",
    TRY_TO_DATE(
    CASE
      WHEN REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(NULLIF(TRIM(TRIM("PS_EXCLUDEDISCHARGEDATEFORLOCADJUSTMENTCODEID")), ''), '[^0-9/.-]+', ''), '[/.]', '-'), '-{2,}', '-') IS NULL THEN NULL
      WHEN REGEXP_LIKE(REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(NULLIF(TRIM(TRIM("PS_EXCLUDEDISCHARGEDATEFORLOCADJUSTMENTCODEID")), ''), '[^0-9/.-]+', ''), '[/.]', '-'), '-{2,}', '-'), '^[0-9]{4}-[0-9]{1,2}-[0-9]{1,2}$') THEN REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(NULLIF(TRIM(TRIM("PS_EXCLUDEDISCHARGEDATEFORLOCADJUSTMENTCODEID")), ''), '[^0-9/.-]+', ''), '[/.]', '-'), '-{2,}', '-')
      WHEN REGEXP_LIKE(REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(NULLIF(TRIM(TRIM("PS_EXCLUDEDISCHARGEDATEFORLOCADJUSTMENTCODEID")), ''), '[^0-9/.-]+', ''), '[/.]', '-'), '-{2,}', '-'), '^[0-9]{1,2}-[0-9]{1,2}-[0-9]{4}$')
        THEN SPLIT_PART(REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(NULLIF(TRIM(TRIM("PS_EXCLUDEDISCHARGEDATEFORLOCADJUSTMENTCODEID")), ''), '[^0-9/.-]+', ''), '[/.]', '-'), '-{2,}', '-'), '-', 3) || '-' ||
             LPAD(SPLIT_PART(REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(NULLIF(TRIM(TRIM("PS_EXCLUDEDISCHARGEDATEFORLOCADJUSTMENTCODEID")), ''), '[^0-9/.-]+', ''), '[/.]', '-'), '-{2,}', '-'), '-', 2), 2, '0') || '-' ||
             LPAD(SPLIT_PART(REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(NULLIF(TRIM(TRIM("PS_EXCLUDEDISCHARGEDATEFORLOCADJUSTMENTCODEID")), ''), '[^0-9/.-]+', ''), '[/.]', '-'), '-{2,}', '-'), '-', 1), 2, '0')
      ELSE NULL
    END
) AS "PS_EXCLUDEDISCHARGEDATEFORLOCADJUSTMENTCODEID",
    TRY_TO_TIMESTAMP(REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(NULLIF(TRIM(TRIM("PS_LASTUPDATE")), ''), '[^0-9/.-]+', ''), '[/.]', '-'), '-{2,}', '-')) AS "PS_LASTUPDATE",
    NULLIF(REGEXP_REPLACE(IFF(LENGTH(REGEXP_REPLACE(NULLIF(TRIM(TRIM("PS_PHONE")), ''), '[^0-9]+', '')) IN (10), REGEXP_REPLACE(NULLIF(TRIM(TRIM("PS_PHONE")), ''), '[^0-9]+', ''), NULL), '^(0+|1+|2+|3+|4+|5+|6+|7+|8+|9+)$', ''), '') AS "PS_PHONE",
    NULLIF(TRIM(TRIM("PS_RPTID")), '') AS "PS_RPTID",
    NULLIF(TRIM(TRIM("PS_FREQUENTLYUSED")), '') AS "PS_FREQUENTLYUSED",
    TRY_TO_TIMESTAMP(REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(NULLIF(TRIM(TRIM("PS_INSERTDATE")), ''), '[^0-9/.-]+', ''), '[/.]', '-'), '-{2,}', '-')) AS "PS_INSERTDATE",
    NULLIF(TRIM(TRIM("PS_REQUIRED")), '') AS "PS_REQUIRED",
    NULLIF(TRIM(TRIM("PS_SLTID")), '') AS "PS_SLTID",
    NULLIF(TRIM(TRIM("PS_DESC")), '') AS "PS_DESC",
    NULLIF(TRIM(TRIM("PS_ELECTRONICELIGIBILITY")), '') AS "PS_ELECTRONICELIGIBILITY",
    NULLIF(TRIM(TRIM("PS_RESOURCEID")), '') AS "PS_RESOURCEID",
    NULLIF(TRIM(TRIM("PS_ENABLEUTILIZATIONGUIDANCEINPOINTCARE")), '') AS "PS_ENABLEUTILIZATIONGUIDANCEINPOINTCARE",
    NULLIF(TRIM(TRIM("PS_FREQ")), '') AS "PS_FREQ",
    NULLIF(TRIM(TRIM("PS_ENABLE_BILLINGAUDIT_HOLDDAYS")), '') AS "PS_ENABLE_BILLINGAUDIT_HOLDDAYS",
    NULLIF(TRIM(TRIM("PS_ENABLENEWMEXICOAUTOMATEDINVOICECREATION")), '') AS "PS_ENABLENEWMEXICOAUTOMATEDINVOICECREATION",
    NULLIF(TRIM(TRIM("PS_EXCLUDEOBTAINADDITIONALAUTHWORKFLOW")), '') AS "PS_EXCLUDEOBTAINADDITIONALAUTHWORKFLOW",
    INITCAP(REGEXP_REPLACE(NULLIF(TRIM(TRIM("PS_CITY")), ''), '[^A-Za-z ]+', '')) AS "PS_CITY",
    NULLIF(TRIM(TRIM("PS_HRTID")), '') AS "PS_HRTID",
    NULLIF(TRIM(TRIM("PS_CAPTURECAREGIVERDETAILS")), '') AS "PS_CAPTURECAREGIVERDETAILS",
    NULLIF(TRIM(TRIM("PS_ENABLE_ADDEDSERVICES")), '') AS "PS_ENABLE_ADDEDSERVICES",
    NULLIF(TRIM(TRIM("PS_FILESPLIT")), '') AS "PS_FILESPLIT",
    NULLIF(TRIM(TRIM("PS_EXCLUDEVERWORKFLOW")), '') AS "PS_EXCLUDEVERWORKFLOW",
    NULLIF(TRIM(TRIM("PS_ENABLECASERATEBILLING")), '') AS "PS_ENABLECASERATEBILLING",
    NULLIF(TRIM(TRIM("PS_ENABLEEPAYMENT")), '') AS "PS_ENABLEEPAYMENT",
    TRY_TO_TIMESTAMP(NULLIF(TRIM(TRIM("CDC_TS")), '')) AS "CDC_TS",
    NULLIF(TRIM(TRIM("PS_FAX")), '') AS "PS_FAX",
    NULLIF(TRIM(TRIM("PS_BAPID")), '') AS "PS_BAPID",
    CASE 
     WHEN NULLIF(TRIM(TRIM("PS_ZIP")), '') IS NULL THEN NULL
     ELSE REGEXP_REPLACE(NULLIF(TRIM(TRIM("PS_ZIP")), ''), '[^0-9]+', '')
 END AS "PS_ZIP",
    NULLIF(TRIM(TRIM("PS_AGENCYCONTACT")), '') AS "PS_AGENCYCONTACT",
    NULLIF(TRIM(TRIM("PS_EXCLUDEFROMMONTHLYREVERIFYWORKFLOW")), '') AS "PS_EXCLUDEFROMMONTHLYREVERIFYWORKFLOW",
    NULLIF(TRIM(TRIM("PS_SHOWPATIENTCARETIME")), '') AS "PS_SHOWPATIENTCARETIME",
    NULLIF(TRIM(TRIM("PS_ID")), '') AS "PS_ID",
    NULLIF(TRIM("INSERTED_DATE"), '') AS "INSERTED_DATE",
    NULLIF(TRIM(TRIM("INSERTED_BY")), '') AS "INSERTED_BY",
    NULLIF(TRIM("UPDATED_DATE"), '') AS "UPDATED_DATE"

FROM DATA_INGESTION_SOLUTION.BRONZE_HCHB.PAYOR_SOURCES
