{# Automated Python Compilation for Pipeline: PAYOR_SOURCE_BRANCHES_PL #}
{{
    config(
        materialized='incremental',
        unique_key='PSB_PSID',
        incremental_strategy='merge',
        alias='PAYOR_SOURCE_BRANCHES_HCHB_CLEANSED'
    )
}}

SELECT
    NULLIF(TRIM(TRIM("PSB_NPI")), '') AS "PSB_NPI",
    NULLIF(TRIM(TRIM("PSB_PTAID")), '') AS "PSB_PTAID",
    NULLIF(TRIM(TRIM("PSB_TAXID")), '') AS "PSB_TAXID",
    NULLIF(TRIM(TRIM("CDC_OP")), '') AS "CDC_OP",
    NULLIF(TRIM(TRIM("PSB_BRANCHCODE")), '') AS "PSB_BRANCHCODE",
    NULLIF(TRIM(TRIM("PSB_PSID")), '') AS "PSB_PSID",
    IFF(UPPER(INITCAP(REGEXP_REPLACE(NULLIF(TRIM(TRIM("PSB_PAYTONAMEOVERRIDE")), ''), '[^A-Za-z ]+', ''))) IN ('TEST','NA','N/A','UNKNOWN','DUMMY','NONE','DEFAULT'), NULL, INITCAP(REGEXP_REPLACE(NULLIF(TRIM(TRIM("PSB_PAYTONAMEOVERRIDE")), ''), '[^A-Za-z ]+', ''))) AS "PSB_PAYTONAMEOVERRIDE",
    NULLIF(TRIM(TRIM("PSB_ZERODOLLARRAP")), '') AS "PSB_ZERODOLLARRAP",
    NULLIF(TRIM(TRIM("PSB_CPID")), '') AS "PSB_CPID",
    IFF(UPPER(INITCAP(REGEXP_REPLACE(NULLIF(TRIM(TRIM("PSB_BILLTONAMEOVERRIDE")), ''), '[^A-Za-z ]+', ''))) IN ('TEST','NA','N/A','UNKNOWN','DUMMY','NONE','DEFAULT'), NULL, INITCAP(REGEXP_REPLACE(NULLIF(TRIM(TRIM("PSB_BILLTONAMEOVERRIDE")), ''), '[^A-Za-z ]+', ''))) AS "PSB_BILLTONAMEOVERRIDE",
    TRY_TO_TIMESTAMP(NULLIF(TRIM(TRIM("CDC_TS")), '')) AS "CDC_TS",
    NULLIF(TRIM(TRIM("PSB_FACILITYID")), '') AS "PSB_FACILITYID",
    NULLIF(TRIM(TRIM("PSB_ID")), '') AS "PSB_ID",
    NULLIF(TRIM(TRIM("PSB_HCFA1500PIN")), '') AS "PSB_HCFA1500PIN",
    NULLIF(TRIM(TRIM("PSB_PROVIDERNO")), '') AS "PSB_PROVIDERNO",
    NULLIF(TRIM(TRIM("PSB_ACTIVE")), '') AS "PSB_ACTIVE",
    NULLIF(TRIM("INSERTED_DATE"), '') AS "INSERTED_DATE",
    NULLIF(TRIM(TRIM("INSERTED_BY")), '') AS "INSERTED_BY",
    NULLIF(TRIM("UPDATED_DATE"), '') AS "UPDATED_DATE"

FROM DATA_INGESTION_SOLUTION.BRONZE_HCHB.PAYOR_SOURCE_BRANCHES
