{# Automated Python Compilation for Pipeline: PAYOR_TYPES_PL #}
{{
    config(
        materialized='incremental',
        unique_key='PT_ID',
        incremental_strategy='merge',
        alias='PAYOR_TYPES_HCHB_CLEANSED'
    )
}}

SELECT
    TRY_TO_TIMESTAMP(REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(NULLIF(TRIM(TRIM("PT_INSERTDATE")), ''), '[^0-9/.-]+', ''), '[/.]', '-'), '-{2,}', '-')) AS "PT_INSERTDATE",
    NULLIF(TRIM(TRIM("PT_FCID")), '') AS "PT_FCID",
    NULLIF(TRIM(TRIM("PT_ID")), '') AS "PT_ID",
    TRY_TO_TIMESTAMP(REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(NULLIF(TRIM(TRIM("PT_LASTUPDATE")), ''), '[^0-9/.-]+', ''), '[/.]', '-'), '-{2,}', '-')) AS "PT_LASTUPDATE",
    NULLIF(TRIM(TRIM("PT_ACTIVE")), '') AS "PT_ACTIVE",
    NULLIF(TRIM(TRIM("PT_WFID")), '') AS "PT_WFID",
    NULLIF(TRIM(TRIM("CDC_OP")), '') AS "CDC_OP",
    NULLIF(TRIM(TRIM("PT_REQUIRED")), '') AS "PT_REQUIRED",
    TRY_TO_TIMESTAMP(NULLIF(TRIM(TRIM("CDC_TS")), '')) AS "CDC_TS",
    NULLIF(TRIM(TRIM("PT_DESC")), '') AS "PT_DESC",
    NULLIF(TRIM(TRIM("PT_SHOWINPROVIDERLINKREFERRAL")), '') AS "PT_SHOWINPROVIDERLINKREFERRAL",
    NULLIF(TRIM(TRIM("PT_GL")), '') AS "PT_GL",
    NULLIF(TRIM("INSERTED_DATE"), '') AS "INSERTED_DATE",
    NULLIF(TRIM(TRIM("INSERTED_BY")), '') AS "INSERTED_BY",
    NULLIF(TRIM("UPDATED_DATE"), '') AS "UPDATED_DATE"

FROM DATA_INGESTION_SOLUTION.BRONZE_HCHB.PAYOR_TYPES
