{# Automated Python Compilation for Pipeline: PROGRAM_NAMES_PL #}
{{
    config(
        materialized='incremental',
        unique_key='PN_ID',
        incremental_strategy='merge',
        alias='PROGRAM_NAMES_HCHB_CLEANSED'
    )
}}

SELECT
    TRY_TO_TIMESTAMP(NULLIF(TRIM(TRIM("CDC_TS")), '')) AS "CDC_TS",
    TRY_TO_TIMESTAMP(REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(NULLIF(TRIM(TRIM("PN_INSERTDATE")), ''), '[^0-9/.-]+', ''), '[/.]', '-'), '-{2,}', '-')) AS "PN_INSERTDATE",
    NULLIF(TRIM(TRIM("SERVICE_LINE")), '') AS "SERVICE_LINE",
    NULLIF(TRIM(TRIM("PN_ID")), '') AS "PN_ID",
    NULLIF(TRIM(TRIM("PN_DESCRIPTION")), '') AS "PN_DESCRIPTION",
    IFF(UPPER(INITCAP(REGEXP_REPLACE(NULLIF(TRIM(TRIM("PN_NAME")), ''), '[^A-Za-z ]+', ''))) IN ('TEST','NA','N/A','UNKNOWN','DUMMY','NONE','DEFAULT'), NULL, INITCAP(REGEXP_REPLACE(NULLIF(TRIM(TRIM("PN_NAME")), ''), '[^A-Za-z ]+', ''))) AS "PN_NAME",
    TRY_TO_TIMESTAMP(REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(NULLIF(TRIM(TRIM("PN_LASTUPDATE")), ''), '[^0-9/.-]+', ''), '[/.]', '-'), '-{2,}', '-')) AS "PN_LASTUPDATE",
    NULLIF(TRIM(TRIM("CDC_OP")), '') AS "CDC_OP",
    NULLIF(TRIM("INSERTED_DATE"), '') AS "INSERTED_DATE",
    NULLIF(TRIM(TRIM("INSERTED_BY")), '') AS "INSERTED_BY",
    NULLIF(TRIM("UPDATED_DATE"), '') AS "UPDATED_DATE"

FROM DATA_INGESTION_SOLUTION.BRONZE_HCHB.PROGRAM_NAMES
