{# Automated Python Compilation for Pipeline: WORKER_BRANCHES_PL #}
{{
    config(
        materialized='incremental',
        unique_key='BRANCH_RESOURCEID',
        incremental_strategy='merge',
        alias='WORKER_BRANCHES_HCHB_CLEANSED'
    )
}}

SELECT
    NULLIF(TRIM(TRIM("WB_WKRID")), '') AS "WB_WKRID",
    NULLIF(TRIM(TRIM("WB_HR")), '') AS "WB_HR",
    NULLIF(TRIM(TRIM("WB_ID")), '') AS "WB_ID",
    TRY_TO_TIMESTAMP(REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(NULLIF(TRIM(TRIM("WB_INSERTDATE")), ''), '[^0-9/.-]+', ''), '[/.]', '-'), '-{2,}', '-')) AS "WB_INSERTDATE",
    NULLIF(TRIM(TRIM("WB_ACTIVE")), '') AS "WB_ACTIVE",
    NULLIF(TRIM(TRIM("WB_PAYROLLBRANCHDRIVEDISTANCEMILES")), '') AS "WB_PAYROLLBRANCHDRIVEDISTANCEMILES",
    NULLIF(TRIM(TRIM("WB_BRANCHCODE")), '') AS "WB_BRANCHCODE",
    NULLIF(TRIM(TRIM("CDC_OP")), '') AS "CDC_OP",
    NULLIF(TRIM(TRIM("WB_DRIVEDISTANCEMILES")), '') AS "WB_DRIVEDISTANCEMILES",
    TRY_TO_TIMESTAMP(REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(NULLIF(TRIM(TRIM("WB_LASTUPDATE")), ''), '[^0-9/.-]+', ''), '[/.]', '-'), '-{2,}', '-')) AS "WB_LASTUPDATE",
    TRY_TO_TIMESTAMP(NULLIF(TRIM(TRIM("CDC_TS")), '')) AS "CDC_TS",
    NULLIF(TRIM(TRIM("WB_PAYROLLBRANCHCODE")), '') AS "WB_PAYROLLBRANCHCODE",
    NULLIF(TRIM("INSERTED_DATE"), '') AS "INSERTED_DATE",
    NULLIF(TRIM(TRIM("INSERTED_BY")), '') AS "INSERTED_BY",
    NULLIF(TRIM("UPDATED_DATE"), '') AS "UPDATED_DATE"

FROM DATA_INGESTION_SOLUTION.BRONZE_HCHB.WORKER_BRANCHES
