{# Automated Python Compilation for Pipeline: WORKER_INTELLIGENT_SCHEDULING_ADDRESS_PL #}
{{
    config(
        materialized='incremental',
        unique_key='WISA_ID',
        incremental_strategy='merge',
        alias='WORKER_INTELLIGENT_SCHEDULING_ADDRESS_HCHB_CLEANSED'
    )
}}

SELECT
    INITCAP(REGEXP_REPLACE(NULLIF(TRIM(TRIM("WISA_STATE")), ''), '[^A-Za-z ]+', '')) AS "WISA_STATE",
    NULLIF(TRIM(TRIM("CDC_OP")), '') AS "CDC_OP",
    TRIM(REGEXP_REPLACE(REGEXP_REPLACE(NULLIF(TRIM(TRIM("WISA_ADDRESSMAPPED")), ''), '[^A-Za-z0-9 ,.#/()_-]+', ''), '[[:space:]]+', ' ')) AS "WISA_ADDRESSMAPPED",
    TRY_TO_TIMESTAMP(REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(NULLIF(TRIM(TRIM("WISA_INSERTDATE")), ''), '[^0-9/.-]+', ''), '[/.]', '-'), '-{2,}', '-')) AS "WISA_INSERTDATE",
    CASE 
     WHEN NULLIF(TRIM(TRIM("WISA_ZIP")), '') IS NULL THEN NULL
     ELSE REGEXP_REPLACE(NULLIF(TRIM(TRIM("WISA_ZIP")), ''), '[^0-9]+', '')
 END AS "WISA_ZIP",
    NULLIF(TRIM(TRIM("WISA_LATLONGMETHOD")), '') AS "WISA_LATLONGMETHOD",
    NULLIF(TRIM(TRIM("WISA_LONGITUDE")), '') AS "WISA_LONGITUDE",
    NULLIF(TRIM(TRIM("WISA_WKRID")), '') AS "WISA_WKRID",
    TRIM(REGEXP_REPLACE(REGEXP_REPLACE(NULLIF(TRIM(TRIM("WISA_STREET")), ''), '[^A-Za-z0-9 ,.#/()_-]+', ''), '[[:space:]]+', ' ')) AS "WISA_STREET",
    TRY_TO_TIMESTAMP(NULLIF(TRIM(TRIM("CDC_TS")), '')) AS "CDC_TS",
    INITCAP(REGEXP_REPLACE(NULLIF(TRIM(TRIM("WISA_CITY")), ''), '[^A-Za-z ]+', '')) AS "WISA_CITY",
    TRY_TO_TIMESTAMP(REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(NULLIF(TRIM(TRIM("WISA_LASTUPDATE")), ''), '[^0-9/.-]+', ''), '[/.]', '-'), '-{2,}', '-')) AS "WISA_LASTUPDATE",
    NULLIF(TRIM(TRIM("WISA_COUNTY")), '') AS "WISA_COUNTY",
    NULLIF(TRIM(TRIM("WISA_LATITUDE")), '') AS "WISA_LATITUDE",
    NULLIF(TRIM(TRIM("WISA_ID")), '') AS "WISA_ID",
    NULLIF(TRIM("INSERTED_DATE"), '') AS "INSERTED_DATE",
    NULLIF(TRIM(TRIM("INSERTED_BY")), '') AS "INSERTED_BY",
    NULLIF(TRIM("UPDATED_DATE"), '') AS "UPDATED_DATE"

FROM DATA_INGESTION_SOLUTION.BRONZE_HCHB.WORKER_INTELLIGENT_SCHEDULING_ADDRESS
